# Create a pod for fileserver, name: 'gop-fileserver'
# pod: gop-fileserver image: 'kodekloud/fileserver'
# pod: gop-fileserver mountPath: '/web'
# pod: gop-fileserver volumeMount name: 'data-store'
# pod: gop-fileserver persistent volume name: data-store
# pod: gop-fileserver persistent volume claim used: 'data-pvc'
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver 
spec:
  volumes:
    - name: data-store 
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
    - name: task-pv-container
      image: 'kodekloud/fileserver'
      volumeMounts:
        - mountPath: "/web"
          name: data-store 
---

# New Service, name: 'gop-fs-service'
# Service name: gop-fs-service, port: '8080'
# Service name: gop-fs-service, targetPort: '8080'
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    app: gop-fileserver 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
