# Create new PersistentVolume = 'data-pv'
# PersistentVolume = data-pv, accessModes = 'ReadWriteMany'
# PersistentVolume = data-pv, hostPath = '/web'
# PersistentVolume = data-pv, storage = '1Gi'
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv 
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/web"
---

# Create new PersistentVolumeClaim = 'data-pvc'
# PersistentVolume = 'data-pvc', accessModes = 'ReadWriteMany'
# PersistentVolume = 'data-pvc', storage request = '1Gi'
# PersistentVolume = 'data-pvc', volumeName = 'data-pv'
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
