---
# Name: drupal-mysql
# Replicas: 1
# Image: mysql:5.7
# Deployment Volume uses PVC : drupal-mysql-pvc
# Volume Mount Path: /var/lib/mysql, subPath: dbdata
# Deployment: 'drupal-mysql' running
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysqlvolume
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc
      containers:
      - name: mysql
        image: mysql:5.7
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysqlvolume
            subPath: dbdata
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret
                key: MYSQL_DATABASE
# This section is bugged in the setup, need to create without it, then uncomment it and kubectl apply the file again to add the env var after initialization has happened to allow it to consider everything complete
          # - name: MYSQL_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: drupal-mysql-secret
          #       key: MYSQL_USER
---
# Name: drupal-mysql-service
# Type: ClusterIP
# Port: 3306
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306