---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   creationTimestamp: "2021-10-20T05:24:20Z"
#   finalizers:
#   - kubernetes.io/pv-protection
#     manager: python-requests
#     operation: Update
#     time: "2021-10-20T05:24:20Z"
#   name: jekyll-site
#   resourceVersion: "937"
#   selfLink: /api/v1/persistentvolumes/jekyll-site
#   uid: 26bdc082-4cfe-4333-a4e3-e568cd99a5b9
# spec:
#   accessModes:
#   - ReadWriteMany
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: /site
#     type: ""
#   persistentVolumeReclaimPolicy: Retain
#   volumeMode: Filesystem
# status:
#   phase: Available